[book]
authors = ["Jeff Zohrab"]
language = "en"
multilingual = false
src = "src"
title = "Lute manual"

[build]
create-missing = true
extra-watch-dirs = [ "css" ]

[output.html]
no-section-label = true
default-theme = "rust"
additional-css = ["css/custom.css"]

[output.html.fold]
enable = true